### ISSUE TITLE
这个汉化有提交给官方吗？

### ISSUE THREAD

**Issue by leafonsword** [moonstack/grafana-for-chinese#1]
如果官方安装包能自带就方便了~

**Comment by 0x01feng** [comment]
我想我在17天之前收到邮件后就回复了, github帐号密码一直懒得找回.

官方答复是, 有多语言的计划,但无具体的时间(这和没有有什么区别?)...

汉化Grafana是个体力活, 我们并不想一直这样, 但目前没有更好的办法

**Comment by leafonsword** [comment]
@0x01feng 确实，估计官方精力有限

**Comment by sylforever98** [comment]
@0x01feng 你那个版本是3.0汉化版，现在官方是5.0版，3。0汉化版可以升级到5.0吗，或者是有没有5.0的汉化版

**Comment by cybfly** [comment]
看来没有
